version: "3"

services: 
    app: 
        build: .
        command: npm run dev
        ports: 
            - "8080:8080"
        volumes: 
            - .:/usr/src/app/
            - nodemodules:/usr/src/app/node_modules
volumes:
    nodemodules: {}  